// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lufzsemnkbqugfvudhab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZnpzZW1ua2JxdWdmdnVkaGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzA1ODYsImV4cCI6MjA2ODc0NjU4Nn0.MNQ0pz2HwB2I0PL79IhpllunI08SjgA-k6ZWz12399w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});